# Generated by Django 2.2.3 on 2019-07-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=128, verbose_name='专辑名称')),
                ('introduction', models.CharField(max_length=256, verbose_name='专辑简介')),
                ('album_img', models.ImageField(blank=True, default='/album/20190723123036845750.jpg', help_text='头像图片的大小规格：256x256，或者对应的比例的图片', null=True, upload_to='album/', verbose_name='歌手海报')),
            ],
            options={
                'verbose_name': '专辑',
                'verbose_name_plural': '专辑',
                'db_table': 'music_album',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=128, verbose_name='歌手名称')),
                ('introduction', models.CharField(max_length=256, verbose_name='歌手简介')),
                ('avatar', models.ImageField(blank=True, default='/avatar/20161202101543717.jpg', help_text='头像图片的大小规格：256x256，或者对应的比例的图片', null=True, upload_to='avatar/', verbose_name='歌手海报')),
            ],
            options={
                'verbose_name': '歌手',
                'verbose_name_plural': '歌手',
                'db_table': 'music_singer',
            },
        ),
        migrations.CreateModel(
            name='SingerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=128, verbose_name='分类名')),
            ],
            options={
                'verbose_name': '歌手分类',
                'verbose_name_plural': '歌手分类',
                'db_table': 'music_singer_category',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=128, verbose_name='歌曲标题')),
                ('length', models.CharField(max_length=32, verbose_name='时长')),
                ('img', models.ImageField(blank=True, default='/img/radio_1.jpg', help_text='头像图', null=True, upload_to='img/', verbose_name='歌曲海报')),
                ('heat', models.CharField(default=None, max_length=128, verbose_name='歌曲收藏数')),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲',
                'db_table': 'music_song',
            },
        ),
        migrations.CreateModel(
            name='SongMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=128, verbose_name='歌单名称')),
                ('introduction', models.CharField(blank=True, max_length=256, null=True, verbose_name='歌单简介')),
                ('menu_img', models.ImageField(blank=True, default='/songmenu/20190722170752290043.jpg', help_text='头像图片的大小规格：256x256，或者对应的比例的图片', null=True, upload_to='songmenu/', verbose_name='歌单图片')),
                ('colnum', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': '歌单',
                'verbose_name_plural': '歌单',
                'db_table': 'music_song_menu',
            },
        ),
        migrations.CreateModel(
            name='SongMenuTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=128, verbose_name='歌单标签名称')),
            ],
            options={
                'verbose_name': '歌单标签',
                'verbose_name_plural': '歌单标签',
                'db_table': 'music_menu_tag',
            },
        ),
    ]
