# Generated by Django 2.2.3 on 2019-07-30 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('song', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='songmenu',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mysongmenus', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='songmenu',
            name='tags',
            field=models.ManyToManyField(db_constraint=False, default='华语', related_name='songmenus', to='song.SongMenuTag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='songmenu',
            name='user',
            field=models.ManyToManyField(blank=True, db_constraint=False, null=True, related_name='songmenus', to=settings.AUTH_USER_MODEL, verbose_name='收藏用户'),
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='song.Album', verbose_name='所属专辑'),
        ),
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='song.Singer', verbose_name='所属歌手'),
        ),
        migrations.AddField(
            model_name='song',
            name='songmenu',
            field=models.ManyToManyField(blank=True, db_constraint=False, null=True, related_name='songs', to='song.SongMenu', verbose_name='所属歌单'),
        ),
        migrations.AddField(
            model_name='singer',
            name='category',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='singers', to='song.SingerCategory', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='singer',
            name='user',
            field=models.OneToOneField(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='singer', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='comment',
            name='menu',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='song.SongMenu', verbose_name='被评论歌单'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='song.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='song',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='song.Song', verbose_name='被评论歌曲'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='song.Singer', verbose_name='所属歌手'),
        ),
    ]
