# Generated by Django 2.2.3 on 2019-07-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190730_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followed_artist',
            new_name='is_artist',
        ),
    ]
